---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: 已知限制可识别此版本产品不支持的平台、设备或功能，或无法与其正确互操作的平台、设备或功能。请仔细查看这些限制。 
---
= 所有云提供商中 Cloud Volumes ONTAP 的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制可识别此版本产品不支持的平台、设备或功能，或无法与其正确互操作的平台、设备或功能。请仔细查看这些限制。

以下限制适用于所有云提供商中的 Cloud Volumes ONTAP：AWS、Azure 和 Google Cloud。



== 不支持的 ONTAP 功能

Cloud Volumes ONTAP 不支持以下功能：

* 聚合级实时重复数据删除
* 聚合级后台重复数据删除
* 磁盘维护中心
* 磁盘清理
* FabricPool 镜像
* Fibre Channel（光纤通道）(FC)
* Flash 池
* 无限卷
* 接口组
* 节点内 LIF 故障转移
* MetroCluster
* 多管理员验证
+
在 Cloud Volumes ONTAP 上启用多管理员验证将导致不支持的配置。

* RAID4、RAID-DP、RAID-TEC（支持 RAID0）
* 服务处理器
* SnapLock Compliance 和企业模式（仅支持 Cloud WORM）
* SnapMirror 同步
* VLAN
* SMB 持续可用性 (CA)
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["连续可用 SMB 共享"^] 不支持无中断操作。





== 最大并发复制操作数

无论实例类型或计算机类型如何，Cloud Volumes ONTAP 的最大并发 SnapMirror 或 SnapVault 传输数为每个节点 100 个。



== 云提供商快照不得用于您的备份和恢复计划

您不应将云提供商的快照用作 Cloud Volumes ONTAP 数据备份和恢复计划的一部分。您应始终使用 ONTAP 快照副本或第三方备份解决方案来备份和恢复托管在 Cloud Volumes ONTAP 上的数据。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["了解如何使用 NetApp Backup and Recovery 来备份和还原 ONTAP 数据"^]。


NOTE: WAFL 文件系统中的 ONTAP 一致性点确定数据一致性。只有 ONTAP 可以静止 WAFL 文件系统以进行崩溃一致性备份。



== Cloud Volumes ONTAP 仅支持预留和按需 VM 实例

Cloud Volumes ONTAP 可以在云提供商提供的保留或按需 VM 实例上运行。不支持其他类型的 VM 实例。



== 不应使用自动应用程序资源管理解决方案

自动应用程序资源管理解决方案不应管理 Cloud Volumes ONTAP 系统。这样做可能会导致对不受支持的配置进行更改。例如，解决方案可能会将 Cloud Volumes ONTAP 更改为不受支持的 VM 实例类型。



== 软件更新必须由 NetApp Console 完成

必须从 NetApp Console 完成 Cloud Volumes ONTAP 的升级。您不应使用 System Manager 或 CLI 升级 Cloud Volumes ONTAP。这样做会影响系统稳定性。



== 不得从云提供商控制台修改 Cloud Volumes ONTAP 部署

从云提供商控制台更改 Cloud Volumes ONTAP 配置会导致不支持的配置。对 Console 创建和管理的 Cloud Volumes ONTAP 资源进行的任何更改都会影响系统稳定性和 Console 管理系统的能力。


NOTE: 初始部署后，支持修改用于 Cloud Volumes ONTAP 资源的 Azure 订阅名称。



== 必须从 Console 管理磁盘和聚合

必须直接从 Console 创建和删除所有磁盘和聚合。您不应该从另一个管理工具执行这些操作。这样做会影响系统稳定性，妨碍将来添加磁盘的能力，并可能产生冗余的云提供商费用。



== SnapManager 许可限制

Cloud Volumes ONTAP 支持 SnapManager 每服务器许可证。不支持每存储系统（SnapManager 套件）许可证。



== 第三方代理和扩展的限制

Cloud Volumes ONTAP 虚拟机实例不支持第三方代理和 VM 扩展。
