---
sidebar: sidebar 
permalink: reference-configs-gcp.html 
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs 
summary: Google Cloud 中支持多种 Cloud Volumes ONTAP 配置。 
---
= Google Cloud 中 Cloud Volumes ONTAP 支持的配置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud 中支持多种 Cloud Volumes ONTAP 配置。



== 按许可证支持的配置

Cloud Volumes ONTAP 在 Google Cloud 中作为单节点系统和高可用性 (HA) 节点对提供，用于容错和无中断操作。

不支持将单节点系统升级到 HA 对。如果要在单节点系统和 HA 对之间切换，则需要部署新系统并将数据从现有系统复制到新系统。

Cloud Volumes ONTAP 可以在云提供商提供的保留或按需 VM 实例上运行。不支持使用其他 VM 实例类型的解决方案。

[role="tabbed-block"]
====
.基于容量的许可证
--
[cols="h,d,d,d"]
|===
|  | 免费增值 | 已优化^4^ | 基于容量的许可证（Essentials 和 Professional） 


| 最大系统容量（磁盘 + 对象存储） | 500 GiB  a| 
借助基于容量的许可，每个 Cloud Volumes ONTAP 系统都支持到对象存储的分层。总分层容量可以扩展到云提供商的存储桶限制。虽然许可证不会施加容量限制，但在配置和管理分层时，应遵循 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool 最佳实践"^]以确保最佳性能、可靠性和成本效益。



| 支持的计算机类型 ^1^  a| 
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64

 a| 
* n2-standard-4
* n2-standard-8

 a| 
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64




| 支持的磁盘类型 ^2^ 3+| 平衡永久磁盘^3^、性能 (SSD) 永久磁盘^3^和标准 (HDD) 永久磁盘。 
|===
注：

. ^1^ 在 Google Cloud 中部署 Cloud Volumes ONTAP 的新实例时，NetApp Console 上不再提供 n1 系列机器供选择。n1 系列机器将仅在较旧的现有系统中保留和支持。Google Cloud 中 Cloud Volumes ONTAP 的新部署仅从 9.8 版本开始受支持。我们建议您切换到与 Cloud Volumes ONTAP 9.8 及更高版本兼容的 n2 系列机器。但是，n1 系列机器将可用于通过 API 进行的新部署。
+
新的 Cloud Volumes ONTAP 系统不再支持 custom-4-16384 机器类型。如果您在此机器类型上运行现有系统，则可以继续使用它，但我们建议切换到 n2-standard-4 机器类型。

. ^2^ 磁盘限制可阻止您单独使用磁盘达到最大系统容量限制。您可以通过 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["将非活动数据分层至对象存储"^]达到容量限制。
+
link:reference-limits-gcp.html["详细了解 Google Cloud 中的磁盘限制"]。

. ^3^ 使用平衡永久磁盘和性能 (SSD) 永久磁盘时，已启用增强的写入性能。
+
从 Cloud Volumes ONTAP 9.13.0 开始，_Flash Cache_、高写入速度和 8,896 字节的更高最大传输单元 (MTU) 可用于以下 HA 对部署实例：

+
** n2-standard-16
** n2-standard-32
** n2-standard-48
** n2-standard-64
+
部署符合条件的实例类型时，可以启用 Flash Cache 和高写入速度。要启用 8,896 字节的更高最大传输单元，必须选择 VPC-1、VPC-2 或 VPC-3 进行部署。更高的 MTU 可实现更高的网络吞吐量。有关启动其中一个部署的更多信息，请参见 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["在 Google Cloud 中启动 HA 对"]。

+

NOTE: _Flash Cache_、高写入模式和 8,896 的 MTU 依赖于功能，并且不能在配置的实例中单独禁用。



. ^4^ 从 2025 年 8 月 11 日开始，Cloud Volumes ONTAP Optimized 许可证已弃用，将无法在 Google Cloud marketplace 中购买或续订现收现付 (PAYGO) 订阅。有关信息，请参阅 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP 的新增功能"^]。


--
.基于节点的许可证
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explore | PAYGO Standard | PAYGO Premium | 基于节点的 BYOL 


| 最大系统容量（磁盘 + 对象存储） | 2 TB ^2^ | 10 TiB | 368 TiB | 每个许可证 368 TiB 


| 支持的机器类型 ^3^  a| 
* n2-standard-4

 a| 
* n1-standard-8 ^3^
* n2-standard-8

 a| 
* n1-standard-32 ^3^
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64

 a| 
* n1-standard-8 ^3^
* n1-standard-32 ^3^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64




| 支持的磁盘类型 4+| 平衡永久磁盘^4^、性能 (SSD) 永久磁盘^4^和标准 (HDD) 永久磁盘。 
|===
注：

. ^1^ 磁盘限制可阻止您单独使用磁盘达到最大系统容量限制。您可以通过 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["将非活动数据分层至对象存储"^]达到容量限制。
+
link:reference-limits-gcp.html["详细了解 Google Cloud 中的磁盘限制"]。

. ^2^ PAYGO Explore 不支持将数据分层到 Google Cloud Storage。
. ^3^ 在 Google Cloud 中部署 Cloud Volumes ONTAP 的新实例时，控制台上不再提供 n1 系列机器供选择。n1 系列机器将仅在较旧的现有系统中保留和支持。仅从 9.8 版本开始，Google Cloud 中才支持 Cloud Volumes ONTAP 的新部署。我们建议您切换到与 Cloud Volumes ONTAP 9.8 及更高版本兼容的 n2 系列机器。但是，n1 系列机器将可用于通过 API 执行的新部署。
+
新的 Cloud Volumes ONTAP 系统不再支持 custom-4-16384 机器类型。如果您在此机器类型上运行现有系统，则可以继续使用它，但我们建议切换到 n2-standard-4 机器类型。

. ^4^ 使用平衡永久磁盘和性能 (SSD) 永久磁盘时，已启用增强的写入性能。


Console 显示了 Standard 和 BYOL 支持的其他机器类型：n1-highmem-4。但是，此机器类型不适用于生产环境。我们已将其仅适用于特定的实验室环境。

从 Cloud Volumes ONTAP 软件版本 9.13.0 开始，Flash Cache、高写入速度和 8,896 字节的更高最大传输单元 (MTU) 可用于以下 HA 对部署实例：

* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64


部署符合条件的实例类型时，可以启用 Flash Cache 和高写入速度。要启用 8,896 字节的更高最大传输单元，必须选择 VPC-1、VPC-2 或 VPC-3 进行部署。更高的 MTU 可实现更高的网络吞吐量。有关启动其中一个部署的更多信息，请参见 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["在 Google Cloud 中启动 HA 对"]。


NOTE: _Flash Cache_、高写入模式和 8,896 的 MTU 依赖于功能，并且不能在配置的实例中单独禁用。

--
====
有关特定机器类型的详细信息，请参阅 Google Cloud 文档：

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["n1 系列通用机型"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["N2 系列通用机型"^]




== 支持的磁盘大小

在 Google Cloud 中，一个聚合最多可包含 6 个类型和大小相同的磁盘。支持以下磁盘大小：

* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 64 TB




== 支持的区域

有关 Google Cloud 区域支持，请参见 https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes 全球区域"^]。
